name: Code style
on:
  - push
  - pull_request

jobs:
  check:
    name: Check style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pre-commit
          pre-commit install
      - name: Check code style
        run: pre-commit run --all-files
